Vagrant.configure("2") do |config|
  config.vm.define "base" do |box|
    box.vm.box = "hashicorp/bionic64"
    box.vm.hostname = 'base'
    box.vm.provision "shell", path: "../common-pkg.sh"
    box.vm.provision "shell", path: "../docker.sh"
    box.vm.provision "shell", path: "../kube.sh"
    box.ssh.insert_key = false
  end
end
