Vagrant.configure("2") do |config|
  config.vm.define "base" do |box|
    box.vm.box = "hashicorp/bionic64"
    box.vm.hostname = 'controller1'
    box.vm.provision "shell", path: "common-pkg.sh"
    box.vm.provision "shell", path: "docker.sh"
    box.vm.provision "shell", path: "kube.sh"
    box.vm.network :public_network, ip: "10.0.0.10", bridge: "en1: Wi-Fi (AirPort)"
    box.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = 2404
        vb.cpus = 2
    end
  end
end
